// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/audio/elevenLabs/audio-isolation': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/elevenLabs/audio-isolation.post').default>>>>
    }
    '/api/audio/elevenLabs/sound-effect-v2': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/elevenLabs/sound-effect-v2.post').default>>>>
    }
    '/api/audio/elevenLabs/speech-to-text': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/elevenLabs/speech-to-text.post').default>>>>
    }
    '/api/audio/elevenLabs/text-to-speech': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/elevenLabs/text-to-speech.post').default>>>>
    }
    '/api/audio/suno/add-instrumental': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/suno/add-instrumental.post').default>>>>
    }
    '/api/audio/suno/add-vocals': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/suno/add-vocals.post').default>>>>
    }
    '/api/audio/suno/extend': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/suno/extend.post').default>>>>
    }
    '/api/audio/suno/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/suno/generate.post').default>>>>
    }
    '/api/audio/suno/upload-cover': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/suno/upload-cover.post').default>>>>
    }
    '/api/audio/suno/upload-extend': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audio/suno/upload-extend.post').default>>>>
    }
    '/api/chat/chatgpt': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/chatgpt.post').default>>>>
    }
    '/api/chat/claude': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/claude.post').default>>>>
    }
    '/api/chat/deepseek': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/deepseek.post').default>>>>
    }
    '/api/chat/gemini': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/gemini.post').default>>>>
    }
    '/api/common/batch-upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/common/batch-upload.post').default>>>>
    }
    '/api/common/models/price': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/common/models/price.get').default>>>>
    }
    '/api/common/models/tree': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/common/models/tree.get').default>>>>
    }
    '/api/image/flux-2-pro/image-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-2-pro/image-to-image.post').default>>>>
    }
    '/api/image/flux-2-pro/text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-2-pro/text-to-image.post').default>>>>
    }
    '/api/image/flux-2/text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-2/text-to-image.post').default>>>>
    }
    '/api/image/flux-kontext/flux-2-image-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-kontext/flux-2-image-to-image.post').default>>>>
    }
    '/api/image/flux-kontext/flux-2-pro-image-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-kontext/flux-2-pro-image-to-image.post').default>>>>
    }
    '/api/image/flux-kontext/flux-2-pro-text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-kontext/flux-2-pro-text-to-image.post').default>>>>
    }
    '/api/image/flux-kontext/flux-2-text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-kontext/flux-2-text-to-image.post').default>>>>
    }
    '/api/image/flux-kontext/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/flux-kontext/generate.post').default>>>>
    }
    '/api/image/gpt-image/image-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/gpt-image/image-to-image.post').default>>>>
    }
    '/api/image/gpt-image/text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/gpt-image/text-to-image.post').default>>>>
    }
    '/api/image/gpt4o-image/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/gpt4o-image/generate.post').default>>>>
    }
    '/api/image/ideogram/character-edit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/character-edit.post').default>>>>
    }
    '/api/image/ideogram/character-remix': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/character-remix.post').default>>>>
    }
    '/api/image/ideogram/character': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/character.post').default>>>>
    }
    '/api/image/ideogram/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/generate.post').default>>>>
    }
    '/api/image/ideogram/v3-edit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/v3-edit.post').default>>>>
    }
    '/api/image/ideogram/v3-reframe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/v3-reframe.post').default>>>>
    }
    '/api/image/ideogram/v3-remix': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/v3-remix.post').default>>>>
    }
    '/api/image/ideogram/v3-text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/ideogram/v3-text-to-image.post').default>>>>
    }
    '/api/image/imagen4/fast-generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/imagen4/fast-generate.post').default>>>>
    }
    '/api/image/imagen4/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/imagen4/generate.post').default>>>>
    }
    '/api/image/imagen4/ultra-generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/imagen4/ultra-generate.post').default>>>>
    }
    '/api/image/nano-banana-2/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/nano-banana-2/generate.post').default>>>>
    }
    '/api/image/nano-banana-pro/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/nano-banana-pro/generate.post').default>>>>
    }
    '/api/image/nano-banana/edit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/nano-banana/edit.post').default>>>>
    }
    '/api/image/nano-banana/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/nano-banana/generate.post').default>>>>
    }
    '/api/image/qwen/image-edit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/qwen/image-edit.post').default>>>>
    }
    '/api/image/qwen/image-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/qwen/image-to-image.post').default>>>>
    }
    '/api/image/qwen/text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/qwen/text-to-image.post').default>>>>
    }
    '/api/image/qwen/z-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/qwen/z-image.post').default>>>>
    }
    '/api/image/seedream/lite-image-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/seedream/lite-image-to-image.post').default>>>>
    }
    '/api/image/seedream/lite-text-to-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/image/seedream/lite-text-to-image.post').default>>>>
    }
    '/api/midjourney/blend': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midjourney/blend.post').default>>>>
    }
    '/api/midjourney/describe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midjourney/describe.post').default>>>>
    }
    '/api/midjourney/imagine': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midjourney/imagine.post').default>>>>
    }
    '/api/midjourney/swap-face': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midjourney/swap-face.post').default>>>>
    }
    '/api/midjourney/upscale': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midjourney/upscale.post').default>>>>
    }
    '/api/midjourney/vary': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midjourney/vary.post').default>>>>
    }
    '/api/news/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/[slug].get').default>>>>
    }
    '/api/news/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/detail.get').default>>>>
    }
    '/api/news': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/index.get').default>>>>
    }
    '/api/news/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/list.get').default>>>>
    }
    '/api/records/chat-detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/chat-detail.get').default>>>>
    }
    '/api/records/detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/detail.get').default>>>>
    }
    '/api/records/extend-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/extend-list.get').default>>>>
    }
    '/api/records/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/records/list.get').default>>>>
    }
    '/api/refund/cancel-subscription': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/refund/cancel-subscription.post').default>>>>
    }
    '/api/refund/refund-recharge-detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/refund/refund-recharge-detail.get').default>>>>
    }
    '/api/refund/refund-recharge': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/refund/refund-recharge.post').default>>>>
    }
    '/api/refund/refund-subscription-detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/refund/refund-subscription-detail.get').default>>>>
    }
    '/api/refund/refund-subscription': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/refund/refund-subscription.post').default>>>>
    }
    '/api/stripe/create-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stripe/create-session.post').default>>>>
    }
    '/api/user/auth/refresh-timezone': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/auth/refresh-timezone.post').default>>>>
    }
    '/api/user/credits-detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/credits-detail.get').default>>>>
    }
    '/api/user/login-by-email': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/login-by-email.post').default>>>>
    }
    '/api/user/send-email-code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/send-email-code.post').default>>>>
    }
    '/api/video/hailuo/image-to-video-pro': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/hailuo/image-to-video-pro.post').default>>>>
    }
    '/api/video/hailuo/image-to-video-standard': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/hailuo/image-to-video-standard.post').default>>>>
    }
    '/api/video/kling/2-6-image-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/2-6-image-to-video.post').default>>>>
    }
    '/api/video/kling/2-6-motion-control': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/2-6-motion-control.post').default>>>>
    }
    '/api/video/kling/2-6-text-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/2-6-text-to-video.post').default>>>>
    }
    '/api/video/kling/3-0-motion-control': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/3-0-motion-control.post').default>>>>
    }
    '/api/video/kling/3-0-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/3-0-video.post').default>>>>
    }
    '/api/video/kling/ai-avatar-pro': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/ai-avatar-pro.post').default>>>>
    }
    '/api/video/kling/ai-avatar-standard': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/ai-avatar-standard.post').default>>>>
    }
    '/api/video/kling/v2-5-turbo-image-to-video-pro': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/v2-5-turbo-image-to-video-pro.post').default>>>>
    }
    '/api/video/kling/v2-5-turbo-text-to-video-pro': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/kling/v2-5-turbo-text-to-video-pro.post').default>>>>
    }
    '/api/video/luma/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/luma/generate.post').default>>>>
    }
    '/api/video/runway/aleph': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/runway/aleph.post').default>>>>
    }
    '/api/video/runway/extend': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/runway/extend.post').default>>>>
    }
    '/api/video/runway/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/runway/generate.post').default>>>>
    }
    '/api/video/seedance/lite-image-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/seedance/lite-image-to-video.post').default>>>>
    }
    '/api/video/seedance/lite-text-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/seedance/lite-text-to-video.post').default>>>>
    }
    '/api/video/seedance/pro-15-image-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/seedance/pro-15-image-to-video.post').default>>>>
    }
    '/api/video/seedance/pro-fast-image-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/seedance/pro-fast-image-to-video.post').default>>>>
    }
    '/api/video/seedance/pro-image-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/seedance/pro-image-to-video.post').default>>>>
    }
    '/api/video/seedance/pro-text-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/seedance/pro-text-to-video.post').default>>>>
    }
    '/api/video/sora-pro/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/sora-pro/generate.post').default>>>>
    }
    '/api/video/sora-pro/storyboard': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/sora-pro/storyboard.post').default>>>>
    }
    '/api/video/sora/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/sora/generate.post').default>>>>
    }
    '/api/video/sora/watermark-remover': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/sora/watermark-remover.post').default>>>>
    }
    '/api/video/veo/extend': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/veo/extend.post').default>>>>
    }
    '/api/video/veo/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/veo/generate.post').default>>>>
    }
    '/api/video/wan/image-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/wan/image-to-video.post').default>>>>
    }
    '/api/video/wan/text-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/wan/text-to-video.post').default>>>>
    }
    '/api/video/wan/video-to-video': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/video/wan/video-to-video.post').default>>>>
    }
    '/sitemap.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}